### ISSUE TITLE
Add salt integrations for autoscaling

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-infrastructure#7]

**Comment by austinpapp** [comment]
a touch vague but if i need to break this up into tasks i will :)

**Comment by jterps08** [comment]
https://github.com/JensRantil/saltstack-autoscaling

**Comment by austinpapp** [comment]
built salt reactors and engine for sqs event handling with guidance from above link

**Comment by austinpapp** [comment]
tested with launch config and autoscaling group. works as designed.

**Comment by austinpapp** [comment]
still a bit unstable. still hacking out the details. the main issue is that the timestamp for the minion coming online and the timestamp for the ec2 instance aren't both being updated. this is preventing the salt master from accepting the key.
